name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      # Step 3: Cache dependencies (optional)
      - name: Cache MkDocs dependencies
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      # Step 5: Build and deploy the site
      - name: Build and deploy MkDocs site
        run: mkdocs gh-deploy --force
